src/beans/Message.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
	private static final long serialVersionUID = 1L;

	private int id;
	private int userId;
	private String text;
	private Date createdDate;
	private Date updatedDate;
	private String subject;
	private String category;
	private String MessageId;


	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	public String getMessageId() {
		return MessageId;
	}
	public void setMessageId(String MessageId) {
		this.MessageId = MessageId;
	}
}

src/beans/UserManagement.java
package beans;

public class UserManagement {

	private int id;
	private int User_status;
	private String Account;
	private String Name;
	private String Branch_id;
	private String Position_id;

	public void setId(int id) {
		this.id = id;
	}
	public int getId() {
		return id;
	}
	public void setUser_status(int User_status) {
		this.User_status = User_status;
	}
	public int getUser_status() {
		return User_status;
	}
	public void setAccount(String Account) {
		this.Account = Account;
	}
	public String getAccount() {
		return Account;
	}
	public void setName(String Name) {
		this.Name = Name;
	}
	public String getName() {
		return Name;
	}
	public void setBranch_id(String Branch_id) {
		this.Branch_id = Branch_id;
	}
	public String getBranch_id() {
		return Branch_id;
	}
	public void setPosition_id(String Position_id) {
		this.Position_id = Position_id;
	}
	public String getPosition_id() {
		return Position_id;
	}

}

src/controller/HomeServlet.java
package controller;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.UserComments;
import beans.UserMessage;
import service.CommentsService;
import service.MessageService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class HomeServlet extends HttpServlet{
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<String> message = new ArrayList<String>();

		String startday = request.getParameter("startday");
		String endday = request.getParameter("endday");
		String serch = request.getParameter("serch");

		if (startday == null || startday.isEmpty()) {
			startday = "2018-01-01";
		}
		if (endday == null || endday.isEmpty()) {
			Date date = new Date();
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
			endday = sdf.format(date.getTime()).toString();
		}

		if (serch == null || serch.isEmpty()){
			serch = "%";
		}
		if ( 10 < serch.length()){
			serch = "%";
		}
		List<UserMessage> messages = new MessageService().getMessage(startday, endday, serch);
		List<UserComments> comments = new CommentsService().getComments();


		if (isValid(request, message) == true) {
			if (request.getParameter("startday") != null || request.getParameter("endday") != null) {
				request.setAttribute("startday", startday);
				request.setAttribute("endday", endday);
			}
			request.setAttribute("messages", messages);
			request.setAttribute("comments", comments);
			request.getRequestDispatcher("/home.jsp").forward(request, response);
		} else {
			request.setAttribute("messages", messages);
			request.setAttribute("comments", comments);
			request.setAttribute("errorMessages",message );
			request.getRequestDispatcher("/home.jsp").forward(request, response);
		}


	}
	private boolean isValid(HttpServletRequest request, List<String> message) {
		String serch = request.getParameter("serch");

		if (serch == null) {
			return true;
		}
		if (10 < serch.length() == true) {
			message.add("カテゴリーは10字以内で入力してください");
		}
		if (message.size() == 0) {
			return true;
		} else {
			return false;
		}

	}
}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.User;
import service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("login.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getServletPath();

		String account = request.getParameter("account");
		String password = request.getParameter("password");
		LoginService loginService = new LoginService();
		User user = loginService.login(account, password);

		HttpSession session = request.getSession();
		if (user != null) {

			session.setAttribute("loginUser", user);
			response.sendRedirect("./");
		} else {

			List<String> messages = new ArrayList<String>();
			messages.add("ログインに失敗しました。");
			request.setAttribute("account",account);
			session.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("login.jsp").forward(request, response);
		}
	}

}

src/controller/ManagementServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.UserManagement;
import service.ManagementService;

@WebServlet(urlPatterns = { "/management" })
public class ManagementServlet  extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {


		List<String> message = new ArrayList<String>();
		UserManagement management = new UserManagement();


		List<UserManagement> managements = new ManagementService().getUserManagement();
		management.setName(request.getParameter("management"));

		request.setAttribute("management", managements);

		request.getRequestDispatcher("management.jsp").forward(request, response);

	}
}

src/controller/MessageServlet.java
package controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.User;

@WebServlet(urlPatterns = { "/messages" })
public class MessageServlet extends HttpServlet{
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {


		User user = (User) request.getSession().getAttribute("loginUser");
		boolean isShowMessageForm;
		if (user != null) {
			isShowMessageForm = true;
		} else {
			isShowMessageForm = false;
		}


		request.setAttribute("isShowMessageForm", isShowMessageForm);
		request.getRequestDispatcher("/messages.jsp").forward(request, response);

	}


}

src/controller/SettingsServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/settings" })
public class SettingsServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();
		List<String> messages = new ArrayList<String>();

		if(request.getParameter("settings") == null && request.getParameter("empid") == null) {
			messages.add("不正な値です");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("management");
			return;
		}
		if(request.getParameter("empid").matches("^[0-9]{1,10}$")==false || request.getParameter("empid") == null || request.getParameter("empid") == ""){
			messages.add("不正な値です");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("management");
			return;
		}

		int i = Integer.parseInt(request.getParameter("empid"));

		User editUser = new UserService().getUser(i);

		if(editUser != null) {
			request.setAttribute("editUser", editUser);
			request.getRequestDispatcher("settings.jsp").forward(request, response);
		} else {
			messages.add("不正な値です");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("management");
		}


	}
	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {


		List<String> messages = new ArrayList<String>();
		HttpSession session = request.getSession();
		User editUser = getEditUser(request);
		session.setAttribute("editUser", editUser);

		if (isValid(request, messages) == true) {
			new UserService().update(editUser);
			request.setAttribute("editUser", editUser);
			response.sendRedirect("management");
		}else {
			request.setAttribute("errorMessages", messages);
			request.setAttribute("editUser", editUser);
			request.getRequestDispatcher("settings.jsp").forward(request, response);
		}
	}

	private User getEditUser(HttpServletRequest request)
			throws IOException, ServletException {

		User editUser = new User();
		editUser.setId(Integer.parseInt(request.getParameter("id")));
		editUser.setName(request.getParameter("name"));
		editUser.setAccount(request.getParameter("account"));
		editUser.setPassword(request.getParameter("password"));
		if (request.getParameter("branch_id") == null) {
			editUser.setBranch_id(0);
		} else {
			int branch_id = Integer.parseInt(request.getParameter("branch_id"));
			editUser.setBranch_id(branch_id);
		}
		if (request.getParameter("position_id") == null) {
			editUser.setPosition_id(0);
		} else {
			int position_id = Integer.parseInt(request.getParameter("position_id"));
			editUser.setPosition_id(position_id);

		}
		return editUser;
	}


	private boolean isValid(HttpServletRequest request, List<String> messages) {

		int id = Integer.parseInt(request.getParameter("id"));
		String name = request.getParameter("name");
		String account = request.getParameter("account");
		String password = request.getParameter("password");
		String checkpassword = request.getParameter("checkPassword");




		if (StringUtils.isEmpty(name) == true) {
			messages.add("名前を入力してください");
		}
		if (10 < name.length()) {
			messages.add("名前は10文字以下で入力してください");
		}
		if (StringUtils.isEmpty(account) == true) {
			messages.add("ログインIDを入力してください");
		}
		if (20 < account.length() || 6 > account.length()) {
			messages.add("ログインIDは6文字以上20文字以下で入力してください");
		}
		if (StringUtils.isEmpty(password) == false) {
			if (20 < password.length() || 6 > password.length()) {
				messages.add("パスワードは6文字以上20文字以下で入力してください");
			}
		}
		if (StringUtils.isEmpty(account) == false) {
			User editUser = new UserService().getUserAccunt(account);
			if (editUser != null ) {
				int userID = editUser.getId();
				if(userID != id ){
					messages.add("同じログインIDが存在します");
				}
			}
		}
		if (!password.equals(checkpassword)) {
			messages.add("確認用パスワードが一致しません");
		}
		if (request.getParameter("branch_id") != null && request.getParameter("position_id") != null) {
			int branch_id = Integer.parseInt(request.getParameter("branch_id"));
			int position_id = Integer.parseInt(request.getParameter("position_id"));
			if ( branch_id == 1 && position_id > 2 ) {
				messages.add("不正な組み合わせです");
			}
		}
		if (request.getParameter("branch_id") != null && request.getParameter("position_id") != null) {
			int branch_id = Integer.parseInt(request.getParameter("branch_id"));
			int position_id = Integer.parseInt(request.getParameter("position_id"));
			if ( branch_id > 1  && position_id <= 2 ) {
				messages.add("不正な組み合わせです");
			}
		}
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}

}

src/controller/SignupServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = {"/signup"})
public class SignupServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {


		request.getRequestDispatcher("signup.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<String> messages = new ArrayList<String>();
		User user = new User();
		user.setName(request.getParameter("name"));
		user.setAccount(request.getParameter("account"));
		user.setPassword(request.getParameter("password"));
		int branch_id = Integer.parseInt(request.getParameter("branch_id"));
		user.setBranch_id(branch_id);
		int position_id = Integer.parseInt(request.getParameter("position_id"));
		user.setPosition_id(position_id);

		if (isValid(request, messages) == true) {

			new UserService().regster(user);
			response.sendRedirect("management");
		} else {
			request.setAttribute("name" , request.getParameter("name"));
			request.setAttribute("account" , request.getParameter("account"));
			request.setAttribute("errorMessages" , messages);
			request.getRequestDispatcher("signup.jsp").forward(request, response);
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {
		String name = request.getParameter("name");
		String account = request.getParameter("account");
		String password = request.getParameter("password");
		String checkPassword = request.getParameter("checkPassword");
		int branch_id = Integer.parseInt(request.getParameter("branch_id"));
		int position_id = Integer.parseInt(request.getParameter("position_id"));


		if (StringUtils.isEmpty(name) == true) {
			messages.add("名前を入力してください");
		}
		if (!StringUtils.isEmpty(name) == true) {
			if (10 < name.length()) {
				messages.add("名前は10文字以下で入力してください");
		}
		}
		if (StringUtils.isEmpty(account) == true) {
			messages.add("ログインIDを入力してください");
		}
		if (!StringUtils.isEmpty(account) == true) {
		if (20 < account.length() || 6 > account.length()) {
			messages.add("ログインIDは6文字以上20文字以下で入力してください");
		}
		}
		if (StringUtils.isEmpty(password) == true) {
			messages.add("パスワードを入力してください");
		}
		if (!StringUtils.isEmpty(password) == true) {
		if (20 < password.length() || 6 > password.length()) {
			messages.add("パスワードは6文字以上20文字以下で入力してください");
		}
		}
		if (StringUtils.isEmpty(account) == false) {
			User editUser = new UserService().getUserAccunt(account);
			if (editUser != null ) {
			messages.add("同じログインIDが存在します");
			}
		}
		if (!password.equals(checkPassword)) {
			messages.add("確認用パスワードが一致しません");
		}
		if (StringUtils.isEmpty(request.getParameter("branch_id")) == true) {
			messages.add("支店を選択してください");
		}
		if (StringUtils.isEmpty(request.getParameter("position_id")) == true) {
			messages.add("役職を選択してください");
		}
		if ( branch_id == 1 && position_id > 2 ) {
			messages.add("不正な組み合わせです");
		}
		if ( branch_id > 1  && position_id <= 2 ) {
			messages.add("不正な組み合わせです");
		}
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}

	}



}

WebContent/header.jsp
<%--
    Author     : tool-taro.com
--%>

<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>header</title>
</head>
<body>
<div class ="header">
	<a href="./">ホーム</a>
	<c:if test="${loginUser.branch_id == 1 }">
		<a href="management">ユーザー管理</a>
	</c:if>
	<a href="messages">新規投稿</a>
	<a href="logout">ログアウト</a>
</div>
</body>
</html>

WebContent/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>社内掲示板</title>
<link rel="stylesheet" type="text/css" href="style.css">
<script type="text/javascript">
<!--

function check(){

	if(window.confirm('送信してよろしいですか？')){ // 確認ダイアログを表示

		return true; // 「OK」時は送信を実行

	}
	else{ // 「キャンセル」時の処理

		window.alert('キャンセルされました'); // 警告ダイアログを表示
		return false; // 送信を中止

	}

}

// -->
</script>

</head>

<body style="word-break: break-all;">
	<div class="header">
		<div class="home">
			<a href="./">
			<img src="home.png" alt="home" width="50" height="50">ホーム
			</a>
			<h1 id="top">
				社内掲示板</h1>
		</div>
		<div class="sonota">
			<c:if test="${ not empty loginUser }">
				ようこそ！
					<c:out value="${loginUser.name}" />さん！
			</c:if>
			<c:if test="${loginUser.branch_id == 1 }">
				<a href="management" class="management">
					<img src="management.png" alt="management" width="50" height="50">ユーザー管理</a>
			</c:if>
			<a href="messages" class="messagenenu">
				<img src="message.png" alt="message" width="50" height="50">新規投稿</a>
					<a href="logout" class="iogout">
						<img src="logout.png" alt="logout" width="50" height="50">ログアウト</a>
		</div>
	</div>
	<br>


	<div class="main-contents">
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li class="errorMessage"><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>
	</div>
	<div class="sertch">
		<form action="./" method="get">
			<input type="date" name="startday" value="${startday}" id="startday">
			から <input type="date" name="endday" value="${endday}" id="endday"><br>
			<input type=text name="serch" id="serch" placeholder="カテゴリー"><br>
			<input type="submit" value="検索する"><br>
		</form>
		<form action="./" method="get">
			<input type="submit" name="reset" value="リセット"
				style="color: #FF0000;">
		</form>

	</div>


	<c:if test="${ not empty loginUser }">
		<br>
		<c:forEach var="message" items="${messages}">
			<div class="message">
				<div class="subject">
					件名：
					 <c:out value="${message.subject}" />
				</div>
			<div class="date">
					<span class="name">投稿者：<c:out value="${message.name}" /></span>
				</div>
									<div class="textcss">
				<c:forEach var="texts" items="${fn:split(message.text, '
				')}">
					<div>
						<c:out value="${texts}" />
					</div>
				</c:forEach>
</div>
				<div class="category">
					カテゴリー：
					<c:out value="${message.category}" />
				</div>
				<div class="account-name">
										投稿日時：
					<fmt:formatDate value="${message.created_date}"
						pattern="yyyy/MM/dd HH:mm:ss" />				</div>

				<form action="delete" method="post" onSubmit="return check()">
					<c:if test="${loginUser.id == message.userId }">
						<input name="MessageId" value="${message.id}" id="MessageId"
							type="hidden" />
						<input type="submit" value="投稿を削除する" style="color: #FF0000;" >
					</c:if>
				</form>
				<br>
				<c:forEach items="${comments}" var="comment">
					<c:if test="${comment.messagesId == message.id }">
						<div class="message2">
						<div class="commenttitle">
						コメント
						</div>
						<div class="comments">
							<c:forEach var="comments"
								items="${fn:split(comment.text, '
				')}">
								<div class="text">

									<c:out value="${comments}" />
								</div>
							</c:forEach>
							</div>
							<div class="account-name">
								<span class="name">コメント投稿者：<c:out value="${comment.name}" /></span>
							</div>
							<div class="date">
								投稿日時：
								<fmt:formatDate value="${comment.created_date}"
									pattern="yyyy/MM/dd HH:mm:ss" />
							</div>
							<c:if test="${loginUser.id == comment.userId }">
								<form action="delete" method="post" onSubmit="return check()">
									<input name="CommentsId" value="${comment.id}" id="CommentsId"
										type="hidden" /> <input type="submit" value="コメントを削除する"
										style="color: #FF0000;">
								</form>
							</c:if>
						</div>
						<br>
					</c:if>
				</c:forEach>
				<form action="newComments" method="post">
					<br /> <input name="CommentsId" value="${message.id}"
						id="CommentsId" type="hidden" />
					<textarea name="Comments" cols="70" rows="5" class="tweet-box"></textarea>
					<br /> <input type="submit" value="投稿にコメントする">500字まで
				</form>
			</div>
			<br>
		</c:forEach>
	</c:if>
</body>
</html>

WebContent/management.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー管理</title>
<link rel="stylesheet" type="text/css" href="style.css">
<script type="text/javascript">
<!--
	function check() {

		if (window.confirm('送信してよろしいですか？')) { // 確認ダイアログを表示

			return true; // 「OK」時は送信を実行

		} else { // 「キャンセル」時の処理

			window.alert('キャンセルされました'); // 警告ダイアログを表示
			return false; // 送信を中止

		}

	}
// -->
</script>

</head>
<body>

<div class="header">
<div class="home">
	<a href="./" ><img src="home.png" alt="home" width="50" height="50">ホーム</a>
	<h1 id="top">社内掲示板 - ユーザー管理</h1>
</div>
<div class="sonota">

<c:if test="${ not empty loginUser }">
					ようこそ！<c:out value="${loginUser.name}" />さん！
	</c:if>

	<c:if test="${loginUser.branch_id == 1 }">
		<a href="signup" class="signup"><img src="signup.png" alt="signup" width="50" height="50">ユーザー登録</a>
	</c:if>
	<a href="messages" class="messagenenu" ><img src="message.png" alt="message" width="50" height="50">新規投稿</a>
	<a href="logout" class="iogout"><img src="logout.png" alt="logout" width="50" height="50">ログアウト</a>
</div>
</div>
	<div class="main-contents">
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li class="errorMessage"><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>

	</div>

<div>
	<c:if test="${ not empty loginUser }">
		<table  border="1" align="left" class="tableCss">
			<tr>
				<th>名前</th>
				<th>ログインID</th>
				<th>所属</th>
				<th>役職</th>
				<th>アカウント状態</th>
			</tr>
			<c:forEach items="${management}" var="management">
				<tr>
					<td><c:out value="${management.name}" /></td>
					<td><c:out value="${management.account}" /></td>
					<td><c:out value="${management.branch_id}" /></td>
					<td><c:out value="${management.position_id}" /></td>
					<c:if test="${management.user_status == 0 }">
						<td><a>通常</a></td>
					</c:if>
					<c:if test="${management.user_status == 1}">
						<td><a style="color: #FF0000;">停止中</a></td>
					</c:if>
					<c:if test="${management.position_id == 総務人事担当者}">
						<td><a></a></td>
					</c:if>
					<td><c:if test="${management.id != loginUser.id }">
							<form action="userStatus" method="post" onSubmit="return check()">
								<input name="MessageId" value="${management.id}" id="MessageId"
									type="hidden" /> <input name="UserStatus"
									value="${management.user_status}" id="UserStatus" type="hidden" />
								<c:if test="${ management.user_status == 0 }">
									<input type="submit" value="アカウントを停止" style="color: #FF0000;">
								</c:if>
								<c:if test="${ management.user_status ==  1}">
									<input type="submit" value="停止解除">
								</c:if>
							</form>
						</c:if></td>
					<td><a href="settings?empid=${management.id}">編集 </a></td>
				</tr>
			</c:forEach>
		</table>
	</c:if>
</div>
</body>
</html>